### ISSUE TITLE
Documentation suggestions

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/tripal_apollo#109]
Based on conversations with @childers and @deming7h777 , we have 2 suggestions:

- https://github.com/NAL-i5K/tripal_apollo/#creating-an-apollo-instance - the term 'Apollo instance' is a bit confusing, because this could also mean setting up the Apollo app. Is there a different way to describe this? Maybe 'Tripal Apollo instance'?
- The assumptions that the tripal_apollo module makes about how the Apollo2 groups are set up aren't documented as far as we can tell - can you add a section on this?

**Comment by bradfordcondon** [comment]
How about if i rename that area "adding an apollo instance to tripal"? 

second point: fully agreed?

**Comment by mpoelchau** [comment]
point 1 - sure!

**Comment by bradfordcondon** [comment]
pt 1: renamed the header:

https://tripal-apollo.readthedocs.io/en/latest/installation.html#adding-an-apollo-instance-to-tripal

<img width="841" alt="screen shot 2018-11-08 at 4 08 04 pm" src="https://user-images.githubusercontent.com/7063154/48227500-86127900-e370-11e8-897f-c94105dcee2c.png">

Apollo 2 group assumptions are here:  

https://tripal-apollo.readthedocs.io/en/latest/apollo_config.html

We could consider adding a warning in the apollo instance creation as well (similar to the warning about Apollo 1 naming that currently appears if you select Apollo 1 as the instance type). 

Or we could just link to the docuemntation website. I maybe like that idea more...

**Comment by bradfordcondon** [comment]
added to form as:

<img width="1462" alt="screen shot 2018-11-08 at 4 37 49 pm" src="https://user-images.githubusercontent.com/7063154/48228936-a6443700-e374-11e8-8be4-0301be6b1c89.png">

If you have more feedback on the new readhtedocs site would love it, please create new issues thanks! 👍
