### ISSUE TITLE
Should Apollo user info mirror the drupal site

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/tripal_apollo#14]
right now, users submit a name and email for apollo registration.  We already have this information because you must have a Drupal account to reach the registration page.

The question is, should we continue to allow users to supply new email/names?  If we simply got rid of this information, and used the name/emails stored in the user table instead, we would no longer be storing user emails/names in multiple places which is better for security, and better SQL practice in general to not store the same info multiple places.

On the other hand, this may be a desired feature.  users want to use multiple names/email addresses for different organisms, and/or different info for the drupal site vs apollo.  

## Passwords

I'm not discussing passwords here, since single-account signon isnt in current scope.  We will continue to have separate Apollo passwords.

**Comment by bradfordcondon** [comment]
Note this issue blocks solidifying schema discussion #10 .  The summary is the old schema **does not link drupal users and web apollo users** and my proposed new schema does.  We could decide to only store drupal user_id, apollo instance, and password for that instance (cut email name as that would be in user).

Note also institution would have to stay in the schema for now (eventually it could og into chado.contact.)

**Comment by mpoelchau** [comment]
@bradfordcondon note that users don't need a Drupal account to access the Apollo registration page. (They do for the data submission page, though)

**Comment by bradfordcondon** [comment]
thanks for the input @mpoelchau 

The module defines a permission for that page, but i forgot to check against your site config: you do indeed give that permission to anonymous users.

This doesn't set me back too much as I can make the Drupal UID link nullable, and not expect/demand it.

I do think its worth discussing requiring users to register to access this page on your site.  Benefits include

* integrating users into Chado as contacts
* single point of access for spam prevention

That said if a) single sign-on is not an option, and b) you dont want users to have two sets of login, then I think we'll need to keep support for anonymous registration.
