### ISSUE TITLE
firstname and lastname inferred by exploding users name

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/tripal_apollo#40]
the fname and lname parameters are required by the python script, and retrieved like so:

```
 $name = explode(" ", $values['name'], 2);
    $fname = $name[0];
    $lname = $name[1];
```

However the instructions don't dictate you need to provide your first and last name separated by a comma.  If you dont do that, does the script error?

**Comment by bradfordcondon** [comment]
I added instructions and a failsafe (if no space, then the last name = the first name)

**Comment by mpoelchau** [comment]
@bradfordcondon is it possible to update this such that if a user enters more than 2 space-separated strings, the first string will be put into firstname and all the rest will be put into lastname?

I know that this won't work well for all names, but at least it captures all the information somehow. This is how @childers migrated all of our previous names into Apollo2.

**Comment by bradfordcondon** [comment]
sure we can do that.  The bigger problem is if a user enters a name iwth no spaces: then it just breaks because you can't have null for last name in Apollo.
