### ISSUE TITLE
delete a user

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/tripal_apollo#58]
request from @mpoelchau : allow admin to DELETE users.  

* on the tripal side deleting a user is no problem.
* so you might have to wipe content before you can delete a user on the apollo side
* on the apollo side, super easy
* if it was linked to a drupal user, we could hook into the user delete event and delete corresponding apollo records.

Further considerations:

you can delete the user unless they have NO privileges left on an instance...

**Comment by bradfordcondon** [comment]
* I'll write an API call that deletes a user from the APOLLO instance.  however chris has warned that might not be sufficient if the user has annotations.  However, I dont see an API service to delete or fetch annotations basd on user- its not clear to me how we could find what annotations that user was responsible for.

**Comment by bradfordcondon** [comment]
from the requests table, click on the user name, which now links to that user's "apollo user page".


<img width="1634" alt="screen shot 2018-10-22 at 3 52 13 pm" src="https://user-images.githubusercontent.com/7063154/47315396-7c6be000-d612-11e8-9296-0e6b4c40abb5.png">


this page, for now, lists all of a given user's requested access.  

<img width="1390" alt="screen shot 2018-10-22 at 3 54 42 pm" src="https://user-images.githubusercontent.com/7063154/47315530-db315980-d612-11e8-9f8e-79897bd3a934.png">

it occurs ot me we should probably link to approve/deny from here as well.

Click delete user, and it will delete this user's record, and all user records on apollo instnaces.  I dont know what/how to do for deleting user annotations so if thats a problem, this wont work.. needs testing.

**Comment by bradfordcondon** [comment]
moving to review/Q&A until we verify this successfully deletes a user, particularly if they have groups and/or annotations.

**Comment by mpoelchau** [comment]
https://github.com/GMOD/Apollo/issues/1937

**Comment by bradfordcondon** [comment]
proposal:

* delete user doesnt attempt to delete the user, but instead removes them from all groups.
* set status to inactive?
* ????? confirm this functionality is as intended

On the drupal side, we deifnitely dont want to be deleting apollo_user records if they arent getting deleted on the apollo end.  Therefore, create a new user status: inactive.  Note that apollo_user_record holds the status (Because each organism will reject/approve a given user).  To prevent confusion with this status column, let's make a is_inactive column on apollo_user instead which defaults to =0

**Comment by bradfordcondon** [comment]
revisiting this issue, since i added a remove from group API as part of #114 . 


(double check there isnt a "remove from all" API to call instead.)

**Comment by bradfordcondon** [comment]
OK, merged!  Im fairly happy with the end result.  We go through and reject the user from all records using the API I built for #110
