### ISSUE TITLE
deleting users is actually hiding rejected requests

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/tripal_apollo#71]
The goal of deleting a user was relaly to hide rejected approval requests.  We can do that with a tabbed approach similar to what im doing in HQ- only show pending requests in the main dashboard and make all requests viewable elsewhere.

**Comment by bradfordcondon** [comment]
see #58.  Note that #58 isnt "wrong" and may be helpful, but really the reuqest was to clean up the display.

**Comment by bradfordcondon** [comment]
@mpoelchau heres the new interface: it defaults to the "pending" tab.  What do you think?

<img width="1510" alt="screen shot 2018-10-23 at 1 40 32 pm" src="https://user-images.githubusercontent.com/7063154/47379571-40e01d00-d6c9-11e8-84f1-3503160018d7.png">

**Comment by mpoelchau** [comment]
Looks good to me!

**Comment by bradfordcondon** [comment]
ok, implemented, keeps the area tidy 👍
