### ISSUE TITLE
Test setup locally

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/tripal_apollo#93]
Looks like this module is ready for testing - specifically, follow the setup instructions to install this module locally. 

https://github.com/NAL-i5K/tripal_apollo#testing-and-development

@deming7h777 @r06942072 @tony006469 would one of you want to try this? It would probably help if you already have Apollo2 set up...

**Comment by deming7h777** [comment]
![perlio](https://user-images.githubusercontent.com/33312760/47975624-94187f00-e07c-11e8-8e5f-7a899660d3ab.PNG)

It seems the procedure  failed when perlIO is buiilding

**Comment by bradfordcondon** [comment]
when are you installing perl? You dont need it for Drupal --  it looks like this is installing JBrowse?

Did you ever get docker set up?  If so you could run the Apollo image instead of trying to install it yourself.

**Comment by bradfordcondon** [comment]
Please look into this: docker toolbox is available for legacy windows systems
https://docs.docker.com/toolbox/toolbox_install_windows/

**Comment by deming7h777** [comment]
![protocal](https://user-images.githubusercontent.com/33312760/48009758-4f2b3180-e0ea-11e8-91ea-c3363f7431b6.PNG)

there is a protocal problem after i finally pull docker file

**Comment by deming7h777** [comment]
> when are you installing perl? You dont need it for Drupal -- it looks like this is installing JBrowse?
> 
> Did you ever get docker set up? If so you could run the Apollo image instead of trying to install it yourself.

this part is for building apollo

**Comment by bradfordcondon** [comment]
any word on this @deming7h777 ?

Your site is running, but the container cant connect to the database (which is running within the container).  It does this via connecting to postgresql on port 5432.  

Is this using docker toolbox on windows, or docker in your VM?

**Comment by deming7h777** [comment]
so now i install docker toolbox on my windows  and pull the image successfully
and solve most of problem due to daemon
![image](https://user-images.githubusercontent.com/33312760/48024256-2e74d300-e10e-11e8-8347-0c7902584428.png)
and now i'm going to run tripal_apollo which is built on docker

**Comment by bradfordcondon** [comment]
BTW to fix the volume mapping error, provide the full path to your directory.

`-v /full/path/to/here:/modules/tripal_apollo`

**Comment by deming7h777** [comment]
![image](https://user-images.githubusercontent.com/33312760/48027146-f6718e00-e115-11e8-8841-dc4dc73f0785.png)
i think every step is completed but still can't run in my browser

**Comment by bradfordcondon** [comment]
that volume mapping is incorrect.  You are providing the DOS formatted path.
type `pwd` that is the path you need to provide.


That said it should give you a drupal site.  What do yo se at localhost?

**Comment by deming7h777** [comment]
1. need to add http:// before local IP(use docker-machine ip)
2. in docker shell we use docker command after go into container that means we are now accessing linux shell
3. "docker run -itd -p 8080:80 -p 5432:5432 --name my-container -v .:/modules/my-module statonlab/tripal3" after pull the tripal3 image u need to map tripal_apollo in your current OS to here for my case, it is my command   "docker run -itd -p 8080:80 -p 5432:5432  -v  /c/Users/user/tripal_apollo/ statonlab/tripal3"
4. you need to git clone tripal_apollo inside your tripal_apollo container if it doesn't exsist (under path:var/www/html/sites/all/modules/custom)
5. build two container one for apollo another for tripal_apollo( 1. docker run -itd -p 8080:80 -p 5432:5432  -v /c/Users/user/tripal_apollo/ statonlab/tripal3
2. docker run -it -v /c/Users/user/tripal_apollo/example_data/:/data  -p 8888:8080 quay.io/gmod/docker-apollo:2.1.0 )
6. need to enable tripal_apollo (use drush pm-enable tripal_apollo -y in container)
7. careful for the memory problem when you build up apollo server at least 2048GB
8. after setting up environment follow  :
      1. add the organism tripal content
      2.  add the Apollo instnace to the tripal site.  See:https://github.com/NAL-i5K/tripal_apollo#creating- 
           an-apollo-instance
      3.  Fill out the user registration form.  request the organism you created.  see: 
           https://github.com/NAL-i5K/tripal_apollo#what-does-tripal-apollo-do
      4.  approve the request.  see:  https://github.com/NAL-i5K/tripal_apollo#approvingdenying-requests
      5.  NOW check your apollo instance to see if the user was created and added to the group.
           NOTE YOU MUST HAVE THE GROUPS SET UP FIRST ON APOLLO
           so if you did not run the travis_set_up.sh script, you can do it manually
           the group names it expects will be obvious when you fill out the form in (2)
-------------------------------------------------------------------------------------------------
issue  :
   1.  the file in usr/share/dict/words can't be empty
   2.  when i check encrypt box and submit it will pop out 500 error (so need to install encypt module)
   3.  after install encrypt module
![image](https://user-images.githubusercontent.com/33312760/48207543-d83aa680-e33e-11e8-9e5b-f61828196ff3.png)
